name: devops-eindproject
services:
  message-queue:
    image: larsdevans/devops.message-queue
    networks:
      - shared
  
  pet-service:
    image: larsdevans/devops.pet-service
    ports:
      - "3001:3000"
    depends_on:
      - message-queue
    networks:
      - shared

  mail-service:
    image: larsdevans/devops.mail-service
    ports:
      - "3002:3000"
    networks:
      - shared

networks:
  shared:
    driver: bridge